import { StateGraph, END, START } from "@langchain/langgraph";
import { ChatOpenAI } from "@langchain/openai";
import { HumanMessage, SystemMessage, BaseMessage } from "@langchain/core/messages";

// 1. Define the State Structure
export interface AgentState {
  messages: BaseMessage[];
  nextAgent: string | null;
  doshaProfile: any;
  currentSymptoms: string[];
  healthScore: number;
  userContext?: any;
}

// 2. Initialize LLM
const llm = new ChatOpenAI({
  modelName: "gpt-4-turbo",
  temperature: 0,
});

// 3. Define the Master Orchestrator Node
const orchestratorNode = async (state: AgentState) => {
  console.log("--- MASTER ORCHESTRATOR ---");
  const lastMessage = state.messages[state.messages.length - 1].content;
  
  const systemPrompt = new SystemMessage(
    `You are the Master Orchestrator of VedaAI, an advanced Preventive Healthcare Operating System.
    Based on the user's latest input, route to the most appropriate specialized agents. If a query is complex, you can route to MULTIPLE agents for a debate/synthesis.
    
    Available Agents:
    - "dosha_agent": Body constitution, Vata/Pitta/Kapha.
    - "symptom_agent": Current physical/mental symptoms.
    - "disease_forecast_agent": Predicting disease risks from habits.
    - "longevity_agent": Biological age, life expectancy.
    - "diet_agent": Meal planning.
    - "food_analysis_agent": Scanning food images.
    - "coach_agent": Motivation, habits, sleep.
    - "research_agent": General Ayurvedic texts lookup.
    - "knowledge_graph_agent": Deep root-cause reasoning.
    
    Respond ONLY with a valid JSON array of strings containing the exact names of the agents. Example: ["diet_agent", "dosha_agent"]`
  );

  const response = await llm.invoke([systemPrompt, new HumanMessage(lastMessage as string)]);
  let nextAgent = response.content.toString().trim();
  
  // Clean up potential markdown formatting from LLM
  if (nextAgent.startsWith('```json')) {
    nextAgent = nextAgent.replace(/```json/g, '').replace(/```/g, '').trim();
  } else if (nextAgent.startsWith('```')) {
    nextAgent = nextAgent.replace(/```/g, '').trim();
  }

  console.log(`[Orchestrator] Routing to: ${nextAgent}`);
  return { nextAgent };
};

const masterSynthesizerNode = async (state: AgentState) => {
  console.log("--- MASTER SYNTHESIZER ---");
  
  const prompt = new SystemMessage(`You are the Master Synthesizer Agent.
  Several specialized agents have just analyzed the user's request. 
  Your job is to read their outputs from the recent conversation history and combine them into a single, cohesive, and easy-to-read response for the user.
  Resolve any conflicts between the agents' advice (Agent Debate) gracefully.
  Do not mention the internal agents by name to the user. Just provide the final synthesized advice.`);

  // Get the original user message
  const userMsg = state.messages.find(m => m.getType() === 'human')?.content || "";
  
  return { messages: [await llm.invoke([prompt, new HumanMessage(`User asked: ${userMsg}\n\nSynthesize the AI responses above into one final answer.`)])] };
};

const reflectionAgentNode = async (state: AgentState) => {
  console.log("--- REFLECTION & SAFETY AGENT ---");
  const lastMessage = state.messages[state.messages.length - 1].content;
  
  const prompt = new SystemMessage(`You are the VedaAI Medical Safety & Reflection Agent.
  Your job is to review the following advice generated by our system.
  Critically evaluate it for:
  1. Medical Safety: Does it recommend something dangerous? Should the user consult a doctor?
  2. Evidence: Is it backed by Ayurvedic or modern medical logic?
  
  If the advice is safe and good, just return the advice as is (improve its formatting if necessary).
  If it is unsafe or requires a doctor's intervention, PREPEND a clear MEDICAL DISCLAIMER to the response advising them to see a doctor immediately.
  `);

  return { messages: [await llm.invoke([prompt, new HumanMessage(lastMessage as string)])] };
};

// 5. Conditional Routing Logic
const routeFromOrchestrator = (state: AgentState) => {
  const agentMap = [
    "dosha_agent", "symptom_agent", "disease_forecast_agent", "longevity_agent", 
    "diet_agent", "food_analysis_agent", "voice_analysis_agent", "face_analysis_agent", 
    "coach_agent", "research_agent", "knowledge_graph_agent", "preventive_care_agent",
    "budget_planner_agent", "hotel_recommendation_agent", "flight_recommendation_agent", "weather_agent"
  ];
  
  try {
    const parsed = JSON.parse(state.nextAgent || "[\"coach_agent\"]");
    if (Array.isArray(parsed)) {
      const validAgents = parsed.filter(a => agentMap.includes(a));
      if (validAgents.length > 0) return validAgents;
    }
  } catch (e) {
    console.error("Failed to parse nextAgent JSON:", e);
  }
  
  return ["coach_agent"]; // Fallback
};

// 4. Define Specialized Agents (12 in total)

const getContextPrompt = (state: AgentState) => {
  return `\n\nUser Context (Past History, Dosha, Symptoms, Lab Reports): ${JSON.stringify(state.userContext || {})}
CRITICAL: You must explain WHY you are making any recommendation based on this User Context. Ground your advice in their personal data and explain the reasoning.
At the very end of your response, you MUST append your Confidence Score and Sources in this exact format on new lines:
Confidence: [XX]%
Sources: [Source 1, Source 2]`;
};

const doshaAgentNode = async (state: AgentState) => {
  const prompt = new SystemMessage(`You are the Dosha Expert Agent. Analyze from Vata, Pitta, Kapha perspective.` + getContextPrompt(state));
  return { messages: [await llm.invoke([prompt, ...state.messages])] };
};

const symptomAgentNode = async (state: AgentState) => {
  const prompt = new SystemMessage(`You are the Symptom Analysis Agent. Evaluate symptoms for early imbalances.` + getContextPrompt(state));
  return { messages: [await llm.invoke([prompt, ...state.messages])] };
};

const diseaseForecastAgentNode = async (state: AgentState) => {
  const prompt = new SystemMessage(`You are the Disease Risk Prediction Model (ML-Simulator).
  Analyze the user's biomarkers, habits, and dosha to output risk probabilities for major diseases (Diabetes, Heart Disease, Hypertension).
  Use advanced prompt-engineering to act as a predictive algorithm.
  Format your output with clear percentages for each disease risk and actionable steps to reduce them.
  ` + getContextPrompt(state));
  return { messages: [await llm.invoke([prompt, ...state.messages])] };
};

const longevityAgentNode = async (state: AgentState) => {
  const prompt = new SystemMessage(`You are the Longevity Engine Agent. Calculate Biological Age and provide anti-aging insights.` + getContextPrompt(state));
  return { messages: [await llm.invoke([prompt, ...state.messages])] };
};

const dietAgentNode = async (state: AgentState) => {
  const prompt = new SystemMessage(`You are the Smart Diet Agent. Generate Dosha-pacifying meal plans.` + getContextPrompt(state));
  return { messages: [await llm.invoke([prompt, ...state.messages])] };
};

const foodAnalysisAgentNode = async (state: AgentState) => {
  const prompt = new SystemMessage(`You are the Food Analysis Agent. In a real environment, you would use Computer Vision to analyze the uploaded food image for calories and Dosha compatibility. For now, simulate this analysis.` + getContextPrompt(state));
  return { messages: [await llm.invoke([prompt, ...state.messages])] };
};

const voiceAnalysisAgentNode = async (state: AgentState) => {
  const prompt = new SystemMessage(`You are the Voice Analysis Agent. Simulate analysis of vocal biomarkers for stress and fatigue.` + getContextPrompt(state));
  return { messages: [await llm.invoke([prompt, ...state.messages])] };
};

const faceAnalysisAgentNode = async (state: AgentState) => {
  const prompt = new SystemMessage(`You are the Face Analysis Agent. Simulate computer vision analysis of facial skin health and hydration.` + getContextPrompt(state));
  return { messages: [await llm.invoke([prompt, ...state.messages])] };
};

const coachAgentNode = async (state: AgentState) => {
  const prompt = new SystemMessage(`You are the AI Health Coach ("Veda" Avatar). Provide daily motivation and habit tracking.` + getContextPrompt(state));
  return { messages: [await llm.invoke([prompt, ...state.messages])] };
};

import { Chroma } from "@langchain/community/vectorstores/chroma";
import { OpenAIEmbeddings } from "@langchain/openai";

const researchAgentNode = async (state: AgentState) => {
  let context = "";
  try {
    const embeddings = new OpenAIEmbeddings({ modelName: "text-embedding-3-small" });
    const vectorStore = await Chroma.fromExistingCollection(embeddings, { collectionName: "veda_knowledge" });
    
    const lastMsg = state.messages[state.messages.length - 1].content as string;
    const results = await vectorStore.similaritySearch(lastMsg, 2);
    context = results.map(r => `Source: ${r.metadata.source} - ${r.pageContent}`).join('\n');
  } catch (err) {
    console.error("RAG Error:", err);
  }

  const prompt = new SystemMessage(`You are the Ayurvedic Research Agent. Provide textbook-backed answers.
  
Retrieved Knowledge Context:
${context}

` + getContextPrompt(state));
  return { messages: [await llm.invoke([prompt, ...state.messages])] };
};

import neo4j from "neo4j-driver";

const knowledgeGraphAgentNode = async (state: AgentState) => {
  let graphContext = "";
  try {
    const driver = neo4j.driver(
      process.env.NEO4J_URI || 'neo4j://localhost',
      neo4j.auth.basic(process.env.NEO4J_USER || 'neo4j', process.env.NEO4J_PASSWORD || 'password')
    );
    const session = driver.session();
    
    // In a real system, you'd extract entities (diseases, symptoms) from the user's message
    // For this implementation, we query a general structure based on their dosha profile or symptoms.
    const cypherQuery = `
      MATCH (d:Disease)-[:HAS_SYMPTOM]->(s:Symptom)
      MATCH (d)-[:TREATED_BY]->(h:Herb)
      RETURN d.name as disease, collect(s.name) as symptoms, collect(h.name) as herbs LIMIT 3
    `;
    
    const result = await session.run(cypherQuery);
    graphContext = result.records.map(record => 
      `Disease: ${record.get('disease')} | Symptoms: ${record.get('symptoms').join(',')} | Herbs: ${record.get('herbs').join(',')}`
    ).join('\n');
    
    await session.close();
    await driver.close();
  } catch (err) {
    console.error("Knowledge Graph Error:", err);
  }

  const prompt = new SystemMessage(`You are the Knowledge Graph Agent. Traverse semantic relationships between diseases, herbs, and Doshas to find root causes.
  
Knowledge Graph Context:
${graphContext}

` + getContextPrompt(state));
  return { messages: [await llm.invoke([prompt, ...state.messages])] };
};

const preventiveCareAgentNode = async (state: AgentState) => {
  const prompt = new SystemMessage(`You are the Preventive Care Agent. Generate proactive warnings before symptoms appear.` + getContextPrompt(state));
  return { messages: [await llm.invoke([prompt, ...state.messages])] };
};

const budgetPlannerAgentNode = async (state: AgentState) => {
  const prompt = new SystemMessage(`You are the Gemini Budget Planner Agent. You help users plan their budget for wellness trips and travel. Analyze their itinerary and provide cost estimations.` + getContextPrompt(state));
  return { messages: [await llm.invoke([prompt, ...state.messages])] };
};

const hotelRecommendationAgentNode = async (state: AgentState) => {
  const prompt = new SystemMessage(`You are the Hotel Recommendation Agent. You recommend wellness resorts, retreats, and hotels based on the user's destination, budget, and Dosha needs.` + getContextPrompt(state));
  return { messages: [await llm.invoke([prompt, ...state.messages])] };
};

const flightRecommendationAgentNode = async (state: AgentState) => {
  const prompt = new SystemMessage(`You are the Flight Recommendation Agent. You suggest flight routes, airlines, and estimates for travel planning.` + getContextPrompt(state));
  return { messages: [await llm.invoke([prompt, ...state.messages])] };
};

const weatherAgentNode = async (state: AgentState) => {
  const prompt = new SystemMessage(`You are the Weather Agent. Provide weather forecasts, seasonal advice, and optimal travel times for destinations.` + getContextPrompt(state));
  return { messages: [await llm.invoke([prompt, ...state.messages])] };
};

const reflectionAgentNode = async (state: AgentState) => {
  console.log("--- REFLECTION & SAFETY AGENT ---");
  const lastMessage = state.messages[state.messages.length - 1].content;
  
  const prompt = new SystemMessage(`You are the VedaAI Medical Safety & Reflection Agent.
  Your job is to review the following advice generated by one of our specialized AI agents.
  Critically evaluate it for:
  1. Medical Safety: Does it recommend something dangerous? Should the user consult a doctor?
  2. Evidence: Is it backed by Ayurvedic or modern medical logic?
  
  If the advice is safe and good, just return the advice as is (improve its formatting if necessary).
  If it is unsafe or requires a doctor's intervention, PREPEND a clear MEDICAL DISCLAIMER to the response advising them to see a doctor immediately.
  `);

  return { messages: [await llm.invoke([prompt, new HumanMessage(lastMessage as string)])] };
};

// 5. Conditional Routing Logic
const routeFromOrchestrator = (state: AgentState) => {
  const agentMap = [
    "dosha_agent", "symptom_agent", "disease_forecast_agent", "longevity_agent", 
    "diet_agent", "food_analysis_agent", "voice_analysis_agent", "face_analysis_agent", 
    "coach_agent", "research_agent", "knowledge_graph_agent", "preventive_care_agent",
    "budget_planner_agent", "hotel_recommendation_agent", "flight_recommendation_agent", "weather_agent"
  ];
  if (state.nextAgent && agentMap.includes(state.nextAgent)) {
    return state.nextAgent;
  }
  return "coach_agent"; // Fallback
};

// 6. Build the LangGraph
export const createVedaOrchestrator = () => {
  
  const graphState = {
    messages: {
      value: (x: BaseMessage[], y: BaseMessage[]) => x.concat(y),
      default: () => [],
    },
    nextAgent: {
      value: (x: string | null, y: string | null) => y ?? x,
      default: () => null,
    },
    doshaProfile: {
      value: (x: any, y: any) => y ?? x,
      default: () => null,
    },
    currentSymptoms: {
      value: (x: string[], y: string[]) => x.concat(y),
      default: () => [],
    },
    healthScore: {
      value: (x: number, y: number) => y ?? x,
      default: () => 100,
    },
    userContext: {
      value: (x: any, y: any) => y ?? x,
      default: () => ({}),
    }
  };

  const workflow = new StateGraph({ channels: graphState as any });

  // Add Nodes
  workflow.addNode("orchestrator", orchestratorNode);
  workflow.addNode("dosha_agent", doshaAgentNode);
  workflow.addNode("symptom_agent", symptomAgentNode);
  workflow.addNode("disease_forecast_agent", diseaseForecastAgentNode);
  workflow.addNode("longevity_agent", longevityAgentNode);
  workflow.addNode("diet_agent", dietAgentNode);
  workflow.addNode("food_analysis_agent", foodAnalysisAgentNode);
  workflow.addNode("voice_analysis_agent", voiceAnalysisAgentNode);
  workflow.addNode("face_analysis_agent", faceAnalysisAgentNode);
  workflow.addNode("coach_agent", coachAgentNode);
  workflow.addNode("research_agent", researchAgentNode);
  workflow.addNode("knowledge_graph_agent", knowledgeGraphAgentNode);
  workflow.addNode("preventive_care_agent", preventiveCareAgentNode);
  workflow.addNode("budget_planner_agent", budgetPlannerAgentNode);
  workflow.addNode("hotel_recommendation_agent", hotelRecommendationAgentNode);
  workflow.addNode("flight_recommendation_agent", flightRecommendationAgentNode);
  workflow.addNode("weather_agent", weatherAgentNode);
  workflow.addNode("master_synthesizer_agent", masterSynthesizerNode);
  workflow.addNode("reflection_agent", reflectionAgentNode);

  // Define Edges
  workflow.addEdge(START, "orchestrator" as any);
  
  workflow.addConditionalEdges(
    "orchestrator" as any,
    routeFromOrchestrator as any,
    {
      dosha_agent: "dosha_agent",
      symptom_agent: "symptom_agent",
      disease_forecast_agent: "disease_forecast_agent",
      longevity_agent: "longevity_agent",
      diet_agent: "diet_agent",
      food_analysis_agent: "food_analysis_agent",
      voice_analysis_agent: "voice_analysis_agent",
      face_analysis_agent: "face_analysis_agent",
      coach_agent: "coach_agent",
      research_agent: "research_agent",
      knowledge_graph_agent: "knowledge_graph_agent",
      preventive_care_agent: "preventive_care_agent",
      budget_planner_agent: "budget_planner_agent",
      hotel_recommendation_agent: "hotel_recommendation_agent",
      flight_recommendation_agent: "flight_recommendation_agent",
      weather_agent: "weather_agent"
    } as any
  );

  const agents = [
    "dosha_agent", "symptom_agent", "disease_forecast_agent", "longevity_agent", 
    "diet_agent", "food_analysis_agent", "voice_analysis_agent", "face_analysis_agent", 
    "coach_agent", "research_agent", "knowledge_graph_agent", "preventive_care_agent",
    "budget_planner_agent", "hotel_recommendation_agent", "flight_recommendation_agent", "weather_agent"
  ];

  // All agents route to master synthesizer
  agents.forEach(agent => workflow.addEdge(agent as any, "master_synthesizer_agent" as any));
  workflow.addEdge("master_synthesizer_agent" as any, "reflection_agent" as any);
  workflow.addEdge("reflection_agent" as any, END);

  return workflow.compile();
};
